# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c76a0b6d3717a31f09e79b85656956f43d729f7ba2253c9a300a4164eced527e975dded24eac6f5236aedaa340ac8358333c4ce18e042e91205b01c9de51b484

test:
  secret_key_base: 817ba76ff691460166c12081bba1765c24ec84c5eca9544b007e64e64443ea9464438581a27acfc8963f2bb0450c50c094a160bce7feb16769080b5a68305680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
